name: publish-to-twitter
description: posts tweets on twitter
author: IntelOwl

inputs:
  api_key:
    description: "Api key"
    required: true
  api_key_secret:
    description: "Api key secret"
    required: true
  access_token:
    description: "Consumer access token"
    required: true
  access_token_secret:
    description: "Consumer access token secret"
    required: true
  status:
    description: "Status to be published to twitter"
    required: true

outputs:
  title:
    description: "Post's title"

runs:
  runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install tweepy

      - name: Run tweet script
        run : python3 script.py

branding:
  icon: "message-circle"
  color: "blue"
