name: "Tweet to Twitter"
description: "Publish a tweet"
author: "IntelOwl"

inputs:
  api_key:
    description: "Api key"
    required: true
  api_key_secret:
    description: "Api key secret"
    required: true
  access_token:
    description: "Consumer access token"
    required: true
  access_token_secret:
    description: "Consumer access token secret"
    required: true
  status:
    description: "Publish notes here"
    required: true

outputs:
  title:
    description: "Post's title"

runs:
  using: "node16"
  main: "index.js"

branding:
  icon: "message-circle"
  color: "blue"